# Azure DevOps Pipeline Template
parameters:
  - name: buildConfiguration
    type: string
    default: 'Release'
  - name: projectName
    type: string
    default: 'MyProject'

variables:
  solution: '$(projectName).sln'
  buildPlatform: 'Any CPU'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: NuGetRestore@1
            displayName: 'Restore NuGet packages'
            inputs:
              solution: '$(solution)'
              feedsToUse: 'config'
              nugetConfigPath: 'nuget.config'
              
          - task: VSBuild@1
            displayName: 'Build solution'
            inputs:
              solution: '$(solution)'
              platform: '$(buildPlatform)'
              configuration: $(buildConfiguration)
              
          - task: VSTest@2
            displayName: 'Run unit tests'
            inputs:
              testSelector: 'testSuite'
              testSuite: '**/*.test.dll'
              platform: '$(buildPlatform)'
              configuration: $(buildConfiguration) 